using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Dynamic;
/**
 * Annotated C# for Profile
 * Generated by CIMTool https://cimtool.ucaiug.io
 */
//  "caseinfo":{
//             "fields":["casenum", "DOR", "caseyear", "CaseSeason", "CaseType", "Comments"], 
//             "data":[0, "2025-07-17T00:00:00", 2025, "winter", "idk", "dummy", 1]
//         }, 

//Area, Bus, Zone, Owner is foreign key for others

public class PsseCase
{
    [Table("CaseInfo")]
    public class CaseInfo
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("CaseNum")]
        public int CaseNum { get; set; }

        [Column("DOR")]
        public DateTime? DOR { get; set; }

        [Column("CaseYear")]
        public int? CaseYear { get; set; }

        [Column("CaseSeason")]
        [StringLength(20)]
        public string? CaseSeason { get; set; }

        [Column("CaseType")]
        [StringLength(50)]
        public string? CaseType { get; set; }

        [Column("Comments")]
        public string? Comments { get; set; }

        [Column("CaseSetNum")]
        public int? CaseSetNum { get; set; }

        [ForeignKey(nameof(CaseSetNum))]
        public virtual CaseSet? CaseSet { get; set; }
    }

    [Table("CaseSet")]
    public class CaseSet
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("CaseSetNum")]
        public int CaseSetNum { get; set; }

        [Column("Name")]
        public string Name { get; set; }

        [Column("Type")]
        public string Type { get; set; }

        [Column("CaseSetYear")]
        public int CaseSetYear { get; set; }

        [Column("Comments")]
        public string Comments{ get; set; }



    }


    [Table("Caseid")]
    public class Caseid
    {
        public Caseid() { }

        public override string ToString() { return this.GetType().Name; }



        [Column("basfrq")]
        public double? Basfrq { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("ic")]
        public int? Ic { get; set; }
        [Column("nxfrat")]
        public int? Nxfrat { get; set; }
        [Column("rev")]
        public int? Rev { get; set; }
        [Column("sbase")]
        public double? Sbase { get; set; }
        [Column("title1")]
        public string? Title1 { get; set; }
        [Column("title2")]
        public string? Title2 { get; set; }
        [Column("xfrrat")]
        public int? Xfrrat { get; set; }

        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }

    }

    [Table("General")]
    public class General
    {
        public General() { }

        public override string ToString() { return this.GetType().Name; }


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("blowup")]
        public double? Blowup { get; set; }
        [Column("camaxreptsln")]
        public int? Camaxreptsln { get; set; }
        [Column("chkdupcntlbl")]
        public int? Chkdupcntlbl { get; set; }
        [Column("maxisollvls")]
        public int? Maxisollvls { get; set; }
        [Column("pqbrak")]
        public double? Pqbrak { get; set; }
        [Column("thrshz")]
        public double? Thrshz { get; set; }
        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Gauss")]
    public class Gauss
    {
        public Gauss() { }

        public override string ToString() { return this.GetType().Name; }



        [Column("accm")]
        public double? Accm { get; set; }
        [Column("accp")]
        public double? Accp { get; set; }
        [Column("accq")]
        public double? Accq { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("itmx")]
        public int? Itmx { get; set; }
        [Column("tol")]
        public double? Tol { get; set; }
        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Newton")]
    public class Newton
    {
        public Newton() { }

        public override string ToString() { return this.GetType().Name; }



        [Column("accn")]
        public double? Accn { get; set; }
        [Column("dvlim")]
        public double? Dvlim { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("itmxn")]
        public int? Itmxn { get; set; }
        [Column("ndvfct")]
        public double? Ndvfct { get; set; }
        [Column("toln")]
        public double? Toln { get; set; }
        [Column("vctolq")]
        public double? Vctolq { get; set; }
        [Column("vctolv")]
        public double? Vctolv { get; set; }
        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Adjust")]
    public class Adjust
    {
        public Adjust() { }

        public override string ToString() { return this.GetType().Name; }


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("acctap")]
        public double? Acctap { get; set; }
        [Column("adjthr")]
        public double? Adjthr { get; set; }
        [Column("mxswim")]
        public int? Mxswim { get; set; }
        [Column("mxtpss")]
        public int? Mxtpss { get; set; }
        [Column("swvbnd")]
        public double? Swvbnd { get; set; }
        [Column("taplim")]
        public int? Taplim { get; set; }
        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }


    [Table("Tysl")]
    public class Tysl
    {
        public Tysl() { }

        public override string ToString() { return this.GetType().Name; }



        [Column("accty")]
        public double? Accty { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("itmxty")]
        public int? Itmxty { get; set; }
        [Column("tolty")]
        public double? Tolty { get; set; }
        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }


    [Table("Solver")]
    public class Solver
    {
        public Solver() { }

        public override string ToString() { return this.GetType().Name; }



        [Column("actaps")]
        public int? Actaps { get; set; }
        [Column("areain")]
        public int? Areain { get; set; }
        [Column("dctaps")]
        public int? Dctaps { get; set; }
        [Column("flatst")]
        public int? Flatst { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("method")]
        public string? Method { get; set; }
        [Column("nondiv")]
        public int? Nondiv { get; set; }
        [Column("phshft")]
        public int? Phshft { get; set; }
        [Column("swshnt")]
        public int? Swshnt { get; set; }
        [Column("varlim")]
        public int? Varlim { get; set; }

        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Rating")]
    public class Rating
    {
        public Rating() { }

        public override string ToString() { return this.GetType().Name; }



        [Column("desc")]
        public string? Desc { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("irate")]
        public int? Irate { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Key]
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }




    [Table("Acline")]
    public class Acline
    {
        public Acline() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("bi")]
        public double? Bi { get; set; }
        [Column("bj")]
        public double? Bj { get; set; }
        [Column("bpu")]
        public double? Bpu { get; set; }
        [Key]
        [Column("ckt")]
        [StringLength(200)] // Avoid key size overflow
        public string? Ckt { get; set; }
        [Column("f1")]
        public double? F1 { get; set; }
        [Column("f2")]
        public double? F2 { get; set; }
        [Column("f3")]
        public double? F3 { get; set; }
        [Column("f4")]
        public double? F4 { get; set; }
        [Column("gi")]
        public double? Gi { get; set; }
        [Column("gj")]
        public double? Gj { get; set; }

        
[Key]
[Column("ibus")]
public int Ibus { get; set; }

[Column("FromBusCaseNumber")]
public int FromBusCaseNumber { get; set; }

public virtual Bus FromBus { get; set; }

        
[Key]
[Column("jbus")]
public int Jbus { get; set; }

[Column("ToBusCaseNumber")]
public int ToBusCaseNumber { get; set; }

public virtual Bus ToBus { get; set; }


        [Column("len")]
        public double? Len { get; set; }
        [Column("met")]
        public int? Met { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("o1")]
public int? O1 { get; set; }

[Column("Owner1CaseNumber")]
public int Owner1CaseNumber { get; set; }

public virtual Owner? Owner1 { get; set; }

[Column("o2")]
public int? O2 { get; set; }

[Column("Owner2CaseNumber")]
public int Owner2CaseNumber { get; set; }

public virtual Owner? Owner2 { get; set; }

[Column("o3")]
public int? O3 { get; set; }

[Column("Owner3CaseNumber")]
public int Owner3CaseNumber { get; set; }

public virtual Owner? Owner3 { get; set; }

[Column("o4")]
public int? O4 { get; set; }

[Column("Owner4CaseNumber")]
public int Owner4CaseNumber { get; set; }

public virtual Owner? Owner4 { get; set; }
        [Column("rate1")]
        public double? Rate1 { get; set; }
        [Column("rate10")]
        public double? Rate10 { get; set; }
        [Column("rate11")]
        public double? Rate11 { get; set; }
        [Column("rate12")]
        public double? Rate12 { get; set; }
        [Column("rate2")]
        public double? Rate2 { get; set; }
        [Column("rate3")]
        public double? Rate3 { get; set; }
        [Column("rate4")]
        public double? Rate4 { get; set; }
        [Column("rate5")]
        public double? Rate5 { get; set; }
        [Column("rate6")]
        public double? Rate6 { get; set; }
        [Column("rate7")]
        public double? Rate7 { get; set; }
        [Column("rate8")]
        public double? Rate8 { get; set; }
        [Column("rate9")]
        public double? Rate9 { get; set; }
        [Column("rpu")]
        public double? Rpu { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("xpu")]
        public double? Xpu { get; set; }
        
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Area")]
    public class Area
    {
        public Area() { }

        public override string ToString() { return this.GetType().Name; }


        [Column("arname")]
        public string? Arname { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("iarea")]
        public int? Iarea { get; set; }
        [Column("isw")]
        public int? Isw { get; set; }
        [Column("pdes")]
        public double? Pdes { get; set; }
        [Column("ptol")]
        public double? Ptol { get; set; }
        
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Bus")]
    public class Bus
    {
        public Bus() { }

        public override string ToString() { return this.GetType().Name; }


        [Column("iarea")]
        public int? Iarea { get; set; }
        public virtual Area? Area { get; set; }
        [Column("baskv")]
        public double? Baskv { get; set; }
        [Column("evhi")]
        public double? Evhi { get; set; }
        [Column("evlo")]
        public double? Evlo { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("ibus")]
        public int Ibus { get; set; }

        [Column("ide")]
        public int? Ide { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("nvhi")]
        public double? Nvhi { get; set; }
        [Column("nvlo")]
        public double? Nvlo { get; set; }

        [Column("iowner")]
        public int? Iowner { get; set; }
        public virtual Owner Owner { get; set; }


        [Column("va")]
        public double? Va { get; set; }
        [Column("vm")]
        public double? Vm { get; set; }


        [Column("zone")]
        public int? ZoneId { get; set; }


        public virtual Zone? Zone { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
        
        [Column("AreaCaseNumber")]
public int AreaCaseNumber { get; set; }

[Column("OwnerCaseNumber")]
public int OwnerCaseNumber { get; set; }

[Column("ZoneCaseNumber")]
public int ZoneCaseNumber { get; set; }

    }




    [Table("Facts")]
    public class Facts
    {
        public Facts() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("fcreg")]
        public int? Fcreg { get; set; }
        [Key]
        [Column("ibus")]
        public int Ibus { get; set; }

        [Column("FromBusCaseNumber")]
        public int FromBusCaseNumber { get; set; }

        public virtual Bus FromBus { get; set; }

        [Column("imx")]
        public double? Imx { get; set; }

        [Key]
        [Column("jbus")]
        public int Jbus { get; set; }

        [Column("ToBusCaseNumber")]
        public int ToBusCaseNumber { get; set; }

        public virtual Bus ToBus { get; set; }

        [Column("linx")]
        public double? Linx { get; set; }
        [Column("mname")]
        public string? Mname { get; set; }
        [Column("mode")]
        public int? Mode { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("nreg")]
        public int? Nreg { get; set; }
        [Column("iowner")]
        public int? Iowner { get; set; }
        public virtual Owner Owner { get; set; }

        [Column("pdes")]
        public double? Pdes { get; set; }
        [Column("qdes")]
        public double? Qdes { get; set; }
        [Column("rmpct")]
        public double? Rmpct { get; set; }
        [Column("set1")]
        public double? Set1 { get; set; }
        [Column("set2")]
        public double? Set2 { get; set; }
        [Column("shmx")]
        public double? Shmx { get; set; }
        [Column("trmx")]
        public double? Trmx { get; set; }
        [Column("vset")]
        public double? Vset { get; set; }
        [Column("vsmx")]
        public double? Vsmx { get; set; }
        [Column("vsref")]
        public int? Vsref { get; set; }
        [Column("vtmn")]
        public double? Vtmn { get; set; }
        [Column("vtmx")]
        public double? Vtmx { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }

        
[Column("OwnerCaseNumber")]
public int OwnerCaseNumber { get; set; }
    }
    [Table("Fixshunt")]
    public class Fixshunt
    {
        public Fixshunt() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("bl")]
        public double? Bl { get; set; }
        [Column("gl")]
        public double? Gl { get; set; }
        [Key]
[Column("ibus")]
public int Ibus { get; set; }

[Column("FromBusCaseNumber")]
public int FromBusCaseNumber { get; set; }

public virtual Bus FromBus { get; set; }
        [Key]
        [Column("shntid")]
        public string? Shntid { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Iatransfer")]
    public class Iatransfer
    {
        public Iatransfer() { }

        public override string ToString() { return this.GetType().Name; }


        //# foreign key for area
        [Key]
        [Column("arfrom")]
        public int Arfrom { get; set; }
        public virtual Area FromArea { get; set; }
        [Column("FromAreaCaseNumber")]
        public int FromAreaCaseNumber { get; set; }


        //# foreign key for area
        [Key]
        [Column("arto")]
        public int Arto { get; set; }
        public virtual Area ToArea { get; set; }
        [Column("ToAreaCaseNumber")]
        public int ToAreaCaseNumber { get; set; }
        [Column("ptran")]
        public double? Ptran { get; set; }
        [Key]
        [Column("trid")]
        public string? Trid { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Indmach")]
    public class Indmach
    {
        public Indmach() { }

        public override string ToString() { return this.GetType().Name; }




        [Column("aconst")]
        public double? Aconst { get; set; }
        [Column("iarea")]
        public int? Iarea { get; set; }
        public virtual Area? Area { get; set; }
        [Column("bc")]
        public int? Bc { get; set; }
        [Column("bconst")]
        public double? Bconst { get; set; }
        [Column("dc")]
        public int? Dc { get; set; }
        [Column("dconst")]
        public double? Dconst { get; set; }
        [Column("e1")]
        public string? E1 { get; set; }
        [Column("e2")]
        public string? E2 { get; set; }
        [Column("econst")]
        public double? Econst { get; set; }
        [Column("hconst")]
        public double? Hconst { get; set; }
        [Column("ia1")]
        public string? Ia1 { get; set; }
        [Column("ia2")]
        public string? Ia2 { get; set; }
        [Key]
        [Column("ibus")]
        public int Ibus { get; set; }

        [Column("FromBusCaseNumber")]
        public int FromBusCaseNumber { get; set; }

        public virtual Bus FromBus { get; set; }
        [Key]
        [Column("imid")]
        public string? Imid { get; set; }
        [Column("mbase")]
        public double? Mbase { get; set; }
        [Column("iowner")]
        public int? Iowner { get; set; }
        public virtual Owner Owner { get; set; }
        [Column("pcode")]
        public int? Pcode { get; set; }
        [Column("pset")]
        public double? Pset { get; set; }
        [Column("r1")]
        public string? R1 { get; set; }
        [Column("r2")]
        public string? R2 { get; set; }
        [Column("ra")]
        public string? Ra { get; set; }
        [Column("ratekv")]
        public double? Ratekv { get; set; }
        [Column("sc")]
        public int? Sc { get; set; }
        [Column("se1")]
        public string? Se1 { get; set; }
        [Column("se2")]
        public string? Se2 { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("tc")]
        public int? Tc { get; set; }
        [Column("x1")]
        public string? X1 { get; set; }
        [Column("x2")]
        public string? X2 { get; set; }
        [Column("x3")]
        public string? X3 { get; set; }
        [Column("xa")]
        public string? Xa { get; set; }
        [Column("xamult")]
        public string? Xamult { get; set; }
        [Column("xm")]
        public string? Xm { get; set; }
        [Column("zone")]
        public int? ZoneId { get; set; }


        public virtual Zone? Zone { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
        
        [Column("AreaCaseNumber")]
public int AreaCaseNumber { get; set; }

[Column("OwnerCaseNumber")]
public int OwnerCaseNumber { get; set; }

[Column("ZoneCaseNumber")]
public int ZoneCaseNumber { get; set; }
    }
    [Table("Load")]
    public class Load
    {
        public Load() { }

        public override string ToString() { return this.GetType().Name; }


        [Column("iarea")]
        public int? Iarea { get; set; }
        public virtual Area? Area { get; set; }
        [Column("dgenm")]
        public int? Dgenm { get; set; }
        [Column("dgenp")]
        public double? Dgenp { get; set; }
        [Column("dgenq")]
        public double? Dgenq { get; set; }
        [Key]
        [Column("ibus")]
        public int Ibus { get; set; }

        [Column("FromBusCaseNumber")]
        public int FromBusCaseNumber { get; set; }

        public virtual Bus FromBus { get; set; }
        [Column("intrpt")]
        public int? Intrpt { get; set; }
        [Column("ip")]
        public double? Ip { get; set; }
        [Column("iq")]
        public double? Iq { get; set; }
        [Key]
        [Column("loadid")]
        public string? Loadid { get; set; }
        [Column("loadtype")]
        public string? Loadtype { get; set; }
        [Column("iowner")]
        public int? Iowner { get; set; }
        public virtual Owner Owner { get; set; }
        [Column("pl")]
        public double? Pl { get; set; }
        [Column("ql")]
        public double? Ql { get; set; }
        [Column("scale")]
        public int? Scale { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("yp")]
        public double? Yp { get; set; }
        [Column("yq")]
        public double? Yq { get; set; }
        [Column("zone")]
        public int? ZoneId { get; set; }


        public virtual Zone? Zone { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
        
        [Column("AreaCaseNumber")]
public int AreaCaseNumber { get; set; }

[Column("OwnerCaseNumber")]
public int OwnerCaseNumber { get; set; }

[Column("ZoneCaseNumber")]
public int ZoneCaseNumber { get; set; }
    }
    [Table("Ntermdc")]
    public class Ntermdc
    {
        public Ntermdc() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("mdc")]
        public int? Mdc { get; set; }
        [Column("name")]
        public string? Name { get; set; }

        [Column("nconv")]
        public int? Nconv { get; set; }
        [Column("ndcbs")]
        public int? Ndcbs { get; set; }
        [Column("ndcln")]
        public int? Ndcln { get; set; }

        [Column("vcmod")]
        public double? Vcmod { get; set; }

        [Key]
        [Column("vconv")]
        public int? Vconv { get; set; }
        [Key]
        [Column("vconvn")]
        public int? Vconvn { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Ntermdcbus")]
    public class Ntermdcbus
    {
        public Ntermdcbus() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("iarea")]
        public int? Iarea { get; set; }
        public virtual Area? Area { get; set; }
        [Column("dcname")]
        public string? Dcname { get; set; }
        [Key]
        [Column("ib")]
        public int? Ib { get; set; }

        [Key]
        [Column("idc")]
        public int? Idc { get; set; }
        [Key]
        [Column("idc2")]
        public int? Idc2 { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("iowner")]
        public int? Iowner { get; set; }
        public virtual Owner Owner { get; set; }
        [Column("rgrnd")]
        public double? Rgrnd { get; set; }
        [Column("zone")]
        public int? ZoneId { get; set; }


        public virtual Zone? Zone { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }

        [Column("AreaCaseNumber")]
        public int AreaCaseNumber { get; set; }

        [Column("OwnerCaseNumber")]
        public int OwnerCaseNumber { get; set; }

    }
    [Table("Ntermdcconv")]
    public class Ntermdcconv
    {
        public Ntermdcconv() { }

        public override string ToString() { return this.GetType().Name; }




        [Column("angmn")]
        public double? Angmn { get; set; }
        [Column("angmx")]
        public double? Angmx { get; set; }
        [Column("cnvcod")]
        public int? Cnvcod { get; set; }
        [Column("dcpf")]
        public double? Dcpf { get; set; }
        [Column("ebas")]
        public double? Ebas { get; set; }
        [Key]
        [Column("ib")]
        public int? Ib { get; set; }
        [Column("marg")]
        public double? Marg { get; set; }
        [Column("n")]
        public int? N { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("rc")]
        public double? Rc { get; set; }
        [Column("setvl")]
        public double? Setvl { get; set; }
        [Column("tap")]
        public double? Tap { get; set; }
        [Column("tpmn")]
        public double? Tpmn { get; set; }
        [Column("tpmx")]
        public double? Tpmx { get; set; }
        [Column("tr")]
        public double? Tr { get; set; }
        [Column("tstp")]
        public double? Tstp { get; set; }
        [Column("xc")]
        public double? Xc { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Ntermdclink")]
    public class Ntermdclink
    {
        public Ntermdclink() { }

        public override string ToString() { return this.GetType().Name; }




        [Key]
        [Column("dcckt")]
        public string? Dcckt { get; set; }
        [Key]
        [Column("idc")]
        public int? Idc { get; set; }
        [Key]
        [Column("jdc")]
        public int? Jdc { get; set; }
        [Column("ldc")]
        public double? Ldc { get; set; }
        [Column("met")]
        public int? Met { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("rdc")]
        public double? Rdc { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Owner")]
    public class Owner
    {
        public Owner() { }

        public override string ToString() { return this.GetType().Name; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("iowner")]
        public int? Iowner { get; set; }
        [Column("owname")]
        public string? Owname { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }


    [Table("Sub")]
    public class Sub
    {
        public Sub() { }

        public override string ToString() { return this.GetType().Name; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("isub")]
        public int Isub { get; set; }
        [Column("lati")]
        public double? Lati { get; set; }
        [Column("long")]
        public double? Long { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("srg")]
        public double? Srg { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Subnode")]
    public class Subnode
    {
        public Subnode() { }

        public override string ToString() { return this.GetType().Name; }

        [Key]
        [Column("ibus")]
        public int Ibus { get; set; }

        [Column("FromBusCaseNumber")]
        public int FromBusCaseNumber { get; set; }

        public virtual Bus FromBus { get; set; }
        [Key]
        [Column("inode")]
        public int? Inode { get; set; }

        [Column("isub")]
        public int? Isub { get; set; }
        public virtual Sub FromSub { get; set; }

        [Column("FromSubCaseNumber")]
        public int FromSubCaseNumber { get; set; }

        
        [Column("name")]
        public string? Name { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("va")]
        public string? Va { get; set; }
        [Column("vm")]
        public string? Vm { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Subswd")]
    public class Subswd
    {
        public Subswd() { }

        public override string ToString() { return this.GetType().Name; }
        [Key]
        [Column("inode")]
        public int? Inode { get; set; }
        [Key]
        [Column("isub")]
        public int? Isub { get; set; }
        [Key]
        [Column("jnode")]
        public int? Jnode { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("nstat")]
        public int? Nstat { get; set; }
        [Column("rate1")]
        public double? Rate1 { get; set; }
        [Column("rate2")]
        public double? Rate2 { get; set; }
        [Column("rate3")]
        public double? Rate3 { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Key]
        [Column("swdid")]
        public string? Swdid { get; set; }
        [Column("type")]
        public int? Type { get; set; }
        [Column("xpu")]
        public double? Xpu { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Swshunt")]
    public class Swshunt
    {
        public Swshunt() { }

        public override string ToString() { return this.GetType().Name; }




        [Column("adjm")]
        public int? Adjm { get; set; }
        [Column("b1")]
        public double? B1 { get; set; }
        [Column("b2")]
        public double? B2 { get; set; }
        [Column("b3")]
        public double? B3 { get; set; }
        [Column("b4")]
        public double? B4 { get; set; }
        [Column("b5")]
        public double? B5 { get; set; }
        [Column("b6")]
        public double? B6 { get; set; }
        [Column("b7")]
        public double? B7 { get; set; }
        [Column("b8")]
        public double? B8 { get; set; }
        [Column("binit")]
        public double? Binit { get; set; }
        [Key]

        [Column("ibus")]
        public int? Ibus { get; set; }
        
        public virtual Bus FromBus { get; set; }
        [Column("modsw")]
        public int? Modsw { get; set; }
        [Column("n1")]
        public int? N1 { get; set; }
        [Column("n2")]
        public int? N2 { get; set; }
        [Column("n3")]
        public int? N3 { get; set; }
        [Column("n4")]
        public int? N4 { get; set; }
        [Column("n5")]
        public int? N5 { get; set; }
        [Column("n6")]
        public int? N6 { get; set; }
        [Column("n7")]
        public int? N7 { get; set; }
        [Column("n8")]
        public int? N8 { get; set; }
        [Column("nreg")]
        public int? Nreg { get; set; }
        [Column("rmidnt")]
        public string? Rmidnt { get; set; }
        [Column("rmpct")]
        public double? Rmpct { get; set; }
        [Column("s1")]
        public int? S1 { get; set; }
        [Column("s2")]
        public int? S2 { get; set; }
        [Column("s3")]
        public int? S3 { get; set; }
        [Column("s4")]
        public int? S4 { get; set; }
        [Column("s5")]
        public int? S5 { get; set; }
        [Column("s6")]
        public int? S6 { get; set; }
        [Column("s7")]
        public int? S7 { get; set; }
        [Column("s8")]
        public int? S8 { get; set; }

        [Key]
        [Column("shntid")]
        public string? Shntid { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("swreg")]
        public int? Swreg { get; set; }
        [Column("vswhi")]
        public double? Vswhi { get; set; }
        [Column("vswlo")]
        public double? Vswlo { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Sysswd")]
    public class Sysswd
    {
        public Sysswd() { }

        public override string ToString() { return this.GetType().Name; }




        [Key]
        [Column("ckt")]
        [StringLength(200)]
        public string? Ckt { get; set; }
        [Key]
[Column("ibus")]
public int Ibus { get; set; }

[Column("FromBusCaseNumber")]
public int FromBusCaseNumber { get; set; }

public virtual Bus FromBus { get; set; }
        [Key]
[Column("jbus")]
public int Jbus { get; set; }

[Column("ToBusCaseNumber")]
public int ToBusCaseNumber { get; set; }

public virtual Bus ToBus { get; set; }
        [Column("met")]
        public int? Met { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("nstat")]
        public int? Nstat { get; set; }
        [Column("rate1")]
        public double? Rate1 { get; set; }
        [Column("rate10")]
        public double? Rate10 { get; set; }
        [Column("rate11")]
        public double? Rate11 { get; set; }
        [Column("rate12")]
        public double? Rate12 { get; set; }
        [Column("rate2")]
        public double? Rate2 { get; set; }
        [Column("rate3")]
        public double? Rate3 { get; set; }
        [Column("rate4")]
        public double? Rate4 { get; set; }
        [Column("rate5")]
        public double? Rate5 { get; set; }
        [Column("rate6")]
        public double? Rate6 { get; set; }
        [Column("rate7")]
        public double? Rate7 { get; set; }
        [Column("rate8")]
        public double? Rate8 { get; set; }
        [Column("rate9")]
        public double? Rate9 { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("stype")]
        public int? Stype { get; set; }
        [Column("xpu")]
        public double? Xpu { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Twotermdc")]
    public class Twotermdc
    {
        public Twotermdc() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("anmni")]
        public double? Anmni { get; set; }
        [Column("anmnr")]
        public double? Anmnr { get; set; }
        [Column("anmxi")]
        public double? Anmxi { get; set; }
        [Column("anmxr")]
        public double? Anmxr { get; set; }
        [Column("cccacc")]
        public double? Cccacc { get; set; }
        [Column("cccitmx")]
        public int? Cccitmx { get; set; }
        [Column("dcvmin")]
        public double? Dcvmin { get; set; }
        [Column("delti")]
        public double? Delti { get; set; }
        [Column("ebasi")]
        public double? Ebasi { get; set; }
        [Column("ebasr")]
        public double? Ebasr { get; set; }
        [Key]
        [Column("ici")]
        public int? Ici { get; set; }
        [Key]
        [Column("icr")]
        public int? Icr { get; set; }
        [Key]
        [Column("idi")]
        public string? Idi { get; set; }
        [Key]
        [Column("idr")]
        public string? Idr { get; set; }
        [Key]
        [Column("ifi")]
        public int? Ifi { get; set; }
        [Key]
        [Column("ifr")]
        public int? Ifr { get; set; }
        [Key]
        [Column("ipi")]
        public int? Ipi { get; set; }

        [Key]
        [Column("ipr")]
        public int? Ipr { get; set; }
        [Key]
        [Column("iti")]
        public int? Iti { get; set; }
        [Key]
        [Column("itr")]
        public int? Itr { get; set; }
        [Column("mdc")]
        public int? Mdc { get; set; }
        [Column("met")]
        public string? Met { get; set; }
        [Key]
        [Column("name")]
        public string? Name { get; set; }
        [Column("nbi")]
        public int? Nbi { get; set; }
        [Key]
        [Column("nbr")]
        public int? Nbr { get; set; }
        [Key]
        [Column("ndi")]
        public int? Ndi { get; set; }
        [Key]
        [Column("ndr")]
        public int? Ndr { get; set; }
        [Column("rci")]
        public double? Rci { get; set; }
        [Column("rcomp")]
        public double? Rcomp { get; set; }
        [Column("rcr")]
        public double? Rcr { get; set; }
        [Column("rdc")]
        public double? Rdc { get; set; }
        [Column("setvl")]
        public double? Setvl { get; set; }
        [Column("stpi")]
        public double? Stpi { get; set; }
        [Column("stpr")]
        public double? Stpr { get; set; }
        [Column("tapi")]
        public double? Tapi { get; set; }
        [Column("tapr")]
        public double? Tapr { get; set; }
        [Column("tmni")]
        public double? Tmni { get; set; }
        [Column("tmnr")]
        public double? Tmnr { get; set; }
        [Column("tmxi")]
        public double? Tmxi { get; set; }
        [Column("tmxr")]
        public double? Tmxr { get; set; }
        [Column("tri")]
        public double? Tri { get; set; }
        [Column("trr")]
        public double? Trr { get; set; }
        [Column("vcmod")]
        public double? Vcmod { get; set; }
        [Column("vschd")]
        public double? Vschd { get; set; }
        [Column("xcapi")]
        public double? Xcapi { get; set; }
        [Column("xcapr")]
        public double? Xcapr { get; set; }
        [Column("xci")]
        public double? Xci { get; set; }
        [Column("xcr")]
        public double? Xcr { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }
    [Table("Vscdc")]
    public class Vscdc
    {
        public Vscdc() { }

        public override string ToString() { return this.GetType().Name; }




        [Column("acset1")]
        public double? Acset1 { get; set; }
        [Column("acset2")]
        public double? Acset2 { get; set; }
        [Column("aloss1")]
        public double? Aloss1 { get; set; }
        [Column("aloss2")]
        public double? Aloss2 { get; set; }
        [Column("bloss1")]
        public double? Bloss1 { get; set; }
        [Column("bloss2")]
        public double? Bloss2 { get; set; }
        [Column("dcset1")]
        public double? Dcset1 { get; set; }
        [Column("dcset2")]
        public double? Dcset2 { get; set; }
        [Column("f1")]
        public double? F1 { get; set; }
        [Column("f2")]
        public double? F2 { get; set; }
        [Column("f3")]
        public double? F3 { get; set; }
        [Column("f4")]
        public double? F4 { get; set; }
        [Key]
        [Column("ibus1")]
        public int? Ibus1 { get; set; }
        [Key]
        [Column("ibus2")]
        public int? Ibus2 { get; set; }
        [Column("imax1")]
        public double? Imax1 { get; set; }
        [Column("imax2")]
        public double? Imax2 { get; set; }
        [Column("maxq1")]
        public double? Maxq1 { get; set; }
        [Column("maxq2")]
        public double? Maxq2 { get; set; }
        [Column("mdc")]
        public int? Mdc { get; set; }
        [Column("minloss1")]
        public double? Minloss1 { get; set; }
        [Column("minloss2")]
        public double? Minloss2 { get; set; }
        [Column("minq1")]
        public double? Minq1 { get; set; }
        [Column("minq2")]
        public double? Minq2 { get; set; }
        [Column("mode1")]
        public int? Mode1 { get; set; }
        [Column("mode2")]
        public int? Mode2 { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("nreg1")]
        public int? Nreg1 { get; set; }
        [Column("nreg2")]
        public int? Nreg2 { get; set; }
[Column("o1")]
public int? O1 { get; set; }

[Column("Owner1CaseNumber")]
public int Owner1CaseNumber { get; set; }

public virtual Owner? Owner1 { get; set; }

[Column("o2")]
public int? O2 { get; set; }

[Column("Owner2CaseNumber")]
public int Owner2CaseNumber { get; set; }

public virtual Owner? Owner2 { get; set; }

[Column("o3")]
public int? O3 { get; set; }

[Column("Owner3CaseNumber")]
public int Owner3CaseNumber { get; set; }

public virtual Owner? Owner3 { get; set; }

[Column("o4")]
public int? O4 { get; set; }

[Column("Owner4CaseNumber")]
public int Owner4CaseNumber { get; set; }

public virtual Owner? Owner4 { get; set; }
        [Column("pwf1")]
        public double? Pwf1 { get; set; }
        [Column("pwf2")]
        public double? Pwf2 { get; set; }
        [Column("rdc")]
        public double? Rdc { get; set; }
        [Column("rmpct1")]
        public double? Rmpct1 { get; set; }
        [Column("rmpct2")]
        public double? Rmpct2 { get; set; }
        [Column("smax1")]
        public double? Smax1 { get; set; }
        [Column("smax2")]
        public double? Smax2 { get; set; }
        [Column("type1")]
        public int? Type1 { get; set; }
        [Column("type2")]
        public int? Type2 { get; set; }

        [Column("vsreg1")]
        public int? Vsreg1 { get; set; }
        [Column("vsreg2")]
        public int? Vsreg2 { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Zone")]
    public class Zone
    {
        public Zone() { }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("izone")]
        public int? Izone { get; set; }

        [Column("zoname")]
        public string? zoname { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }

    }

    [Table("Msline")]
    public class Msline
    {
        public Msline() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("dum1")]
        public int? Dum1 { get; set; }
        [Column("dum2")]
        public int? Dum2 { get; set; }
        [Column("dum3")]
        public int? Dum3 { get; set; }
        [Column("dum4")]
        public int? Dum4 { get; set; }
        [Column("dum5")]
        public int? Dum5 { get; set; }
        [Column("dum6")]
        public int? Dum6 { get; set; }
        [Column("dum7")]
        public int? Dum7 { get; set; }
        [Column("dum8")]
        public int? Dum8 { get; set; }
        [Column("dum9")]
        public int? Dum9 { get; set; }

[Column("Dum1BusCaseNumber")]
public int Dum1BusCaseNumber { get; set; }
public virtual Bus? Dum1Bus { get; set; }

[Column("Dum2BusCaseNumber")]
public int Dum2BusCaseNumber { get; set; }
public virtual Bus? Dum2Bus { get; set; }

[Column("Dum3BusCaseNumber")]
public int Dum3BusCaseNumber { get; set; }
public virtual Bus? Dum3Bus { get; set; }

[Column("Dum4BusCaseNumber")]
public int Dum4BusCaseNumber { get; set; }
public virtual Bus? Dum4Bus { get; set; }

[Column("Dum5BusCaseNumber")]
public int Dum5BusCaseNumber { get; set; }
public virtual Bus? Dum5Bus { get; set; }

[Column("Dum6BusCaseNumber")]
public int Dum6BusCaseNumber { get; set; }
public virtual Bus? Dum6Bus { get; set; }

[Column("Dum7BusCaseNumber")]
public int Dum7BusCaseNumber { get; set; }
public virtual Bus? Dum7Bus { get; set; }

[Column("Dum8BusCaseNumber")]
public int Dum8BusCaseNumber { get; set; }
public virtual Bus? Dum8Bus { get; set; }

[Column("Dum9BusCaseNumber")]
public int Dum9BusCaseNumber { get; set; }
public virtual Bus? Dum9Bus { get; set; }

        
        [Key]
[Column("ibus")]
public int Ibus { get; set; }

[Column("FromBusCaseNumber")]
public int FromBusCaseNumber { get; set; }

public virtual Bus FromBus { get; set; }
        [Key]
[Column("jbus")]
public int Jbus { get; set; }

[Column("ToBusCaseNumber")]
public int ToBusCaseNumber { get; set; }

public virtual Bus ToBus { get; set; }
        [Column("met")]
        public int? Met { get; set; }
        [Key]
        [Column("mslid")]
        public string? Mslid { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Generator")]
    public class Generator
    {
        public Generator() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("baslod")]
        public int? Baslod { get; set; }
        [Column("droopname")]
        public string? Droopname { get; set; }
        [Column("f1")]
        public double? F1 { get; set; }
        [Column("f2")]
        public string? F2 { get; set; }
        [Column("f3")]
        public string? F3 { get; set; }
        [Column("f4")]
        public string? F4 { get; set; }
        [Column("gtap")]
        public double? Gtap { get; set; }
        [Key]
[Column("ibus")]
public int Ibus { get; set; }

[Column("FromBusCaseNumber")]
public int FromBusCaseNumber { get; set; }

public virtual Bus FromBus { get; set; }

        [Column("ireg")]
        public int? Ireg { get; set; }
        [Key]
        [Column("machid")]
        public string? Machid { get; set; }
        [Column("mbase")]
        public double? Mbase { get; set; }
        [Column("nreg")]
        public int? Nreg { get; set; }
 [Column("o1")]
public int? O1 { get; set; }

[Column("Owner1CaseNumber")]
public int Owner1CaseNumber { get; set; }

public virtual Owner? Owner1 { get; set; }

[Column("o2")]
public int? O2 { get; set; }

[Column("Owner2CaseNumber")]
public int Owner2CaseNumber { get; set; }

public virtual Owner? Owner2 { get; set; }

[Column("o3")]
public int? O3 { get; set; }

[Column("Owner3CaseNumber")]
public int Owner3CaseNumber { get; set; }

public virtual Owner? Owner3 { get; set; }

[Column("o4")]
public int? O4 { get; set; }

[Column("Owner4CaseNumber")]
public int Owner4CaseNumber { get; set; }

public virtual Owner? Owner4 { get; set; }
        [Column("pb")]
        public double? Pb { get; set; }
        [Column("pg")]
        public double? Pg { get; set; }
        [Column("pt")]
        public double? Pt { get; set; }
        [Column("qb")]
        public double? Qb { get; set; }
        [Column("qg")]
        public double? Qg { get; set; }
        [Column("qt")]
        public double? Qt { get; set; }
        [Column("rmpct")]
        public double? Rmpct { get; set; }
        [Column("rt")]
        public double? Rt { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("vs")]
        public double? Vs { get; set; }
        [Column("wmod")]
        public int? Wmod { get; set; }
        [Column("wpf")]
        public float? Wpf { get; set; }
        [Column("xt")]
        public double? Xt { get; set; }
        [Column("zr")]
        public double? Zr { get; set; }
        [Column("zx")]
        public double? Zx { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Transformer")]
    public class Transformer
    {
        public Transformer() { }

        public override string ToString() { return this.GetType().Name; }

        [Column("ang1")]
        public double? Ang1 { get; set; }
        [Column("ang2")]
        public string? Ang2 { get; set; }
        [Column("ang3")]
        public string? Ang3 { get; set; }
        [Column("anstar")]
        public string? Anstar { get; set; }

        [Key]
        [Column("ckt")]
        public string? Ckt { get; set; }
        [Column("cm")]
        public int? Cm { get; set; }
        [Column("cnxa1")]
        public double? Cnxa1 { get; set; }
        [Column("cnxa2")]
        public string? Cnxa2 { get; set; }
        [Column("cnxa3")]
        public string? Cnxa3 { get; set; }
        [Column("cod1")]
        public int? Cod1 { get; set; }
        [Column("cod2")]
        public string? Cod2 { get; set; }
        [Column("cod3")]
        public string? Cod3 { get; set; }
        [Column("cont1")]
        public int? Cont1 { get; set; }
        [Column("cont2")]
        public string? Cont2 { get; set; }
        [Column("cont3")]
        public string? Cont3 { get; set; }
        [Column("cr1")]
        public double? Cr1 { get; set; }
        [Column("cr2")]
        public string? Cr2 { get; set; }
        [Column("cr3")]
        public string? Cr3 { get; set; }
        [Column("cw")]
        public int? Cw { get; set; }
        [Column("cx1")]
        public double? Cx1 { get; set; }
        [Column("cx2")]
        public string? Cx2 { get; set; }
        [Column("cx3")]
        public string? Cx3 { get; set; }
        [Column("cz")]
        public int? Cz { get; set; }
        [Column("f1")]
        public double? F1 { get; set; }
        [Column("f2")]
        public double? F2 { get; set; }
        [Column("f3")]
        public double? F3 { get; set; }
        [Column("f4")]
        public double? F4 { get; set; }
        [Key]
[Column("ibus")]
public int Ibus { get; set; }

[Column("FromBusCaseNumber")]
public int FromBusCaseNumber { get; set; }

public virtual Bus FromBus { get; set; }
        [Key]
[Column("jbus")]
public int Jbus { get; set; }

[Column("ToBusCaseNumber")]
public int ToBusCaseNumber { get; set; }

public virtual Bus ToBus { get; set; }
        [Key]
        [Column("kbus")]
        public int Kbus { get; set; }
        [Column("AuxiliaryBusCaseNumber")]
        public int AuxiliaryBusCaseNumber { get; set; }

        public virtual Bus AuxiliaryBus { get; set; }

        [Column("mag1")]
        public double? Mag1 { get; set; }
        [Column("mag2")]
        public double? Mag2 { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("nmet")]
        public int? Nmet { get; set; }
        [Column("node1")]
        public int? Node1 { get; set; }
        [Column("node2")]
        public string? Node2 { get; set; }
        [Column("node3")]
        public string? Node3 { get; set; }
        [Column("nomv1")]
        public double? Nomv1 { get; set; }
        [Column("nomv2")]
        public double? Nomv2 { get; set; }
        [Column("nomv3")]
        public string? Nomv3 { get; set; }
        [Column("ntp1")]
        public int? Ntp1 { get; set; }
        [Column("ntp2")]
        public string? Ntp2 { get; set; }
        [Column("ntp3")]
        public string? Ntp3 { get; set; }
[Column("o1")]
public int? O1 { get; set; }

[Column("Owner1CaseNumber")]
public int Owner1CaseNumber { get; set; }

public virtual Owner? Owner1 { get; set; }

[Column("o2")]
public int? O2 { get; set; }

[Column("Owner2CaseNumber")]
public int Owner2CaseNumber { get; set; }

public virtual Owner? Owner2 { get; set; }

[Column("o3")]
public int? O3 { get; set; }

[Column("Owner3CaseNumber")]
public int Owner3CaseNumber { get; set; }

public virtual Owner? Owner3 { get; set; }

[Column("o4")]
public int? O4 { get; set; }

[Column("Owner4CaseNumber")]
public int Owner4CaseNumber { get; set; }

public virtual Owner? Owner4 { get; set; }
        [Column("r1_2")]
        public double? R1_2 { get; set; }
        [Column("r2_3")]
        public string? R2_3 { get; set; }
        [Column("r3_1")]
        public string? R3_1 { get; set; }
        [Column("rma1")]
        public double? Rma1 { get; set; }
        [Column("rma2")]
        public string? Rma2 { get; set; }
        [Column("rma3")]
        public string? Rma3 { get; set; }
        [Column("rmi1")]
        public double? Rmi1 { get; set; }
        [Column("rmi2")]
        public string? Rmi2 { get; set; }
        [Column("rmi3")]
        public string? Rmi3 { get; set; }
        [Column("sbase1_2")]
        public double? Sbase1_2 { get; set; }
        [Column("sbase2_3")]
        public string? Sbase2_3 { get; set; }
        [Column("sbase3_1")]
        public string? Sbase3_1 { get; set; }
        [Column("stat")]
        public int? Stat { get; set; }
        [Column("tab1")]
        public int? Tab1 { get; set; }
        [Column("tab2")]
        public string? Tab2 { get; set; }
        [Column("tab3")]
        public string? Tab3 { get; set; }
        [Column("vecgrp")]
        public string? Vecgrp { get; set; }
        [Column("vma1")]
        public double? Vma1 { get; set; }
        [Column("vma2")]
        public string? Vma2 { get; set; }
        [Column("vma3")]
        public string? Vma3 { get; set; }
        [Column("vmi1")]
        public double? Vmi1 { get; set; }
        [Column("vmi2")]
        public string? Vmi2 { get; set; }
        [Column("vmi3")]
        public string? Vmi3 { get; set; }
        [Column("vmstar")]
        public string? Vmstar { get; set; }
        [Column("wdg1rate1")]
        public double? Wdg1rate1 { get; set; }
        [Column("wdg1rate10")]
        public double? Wdg1rate10 { get; set; }
        [Column("wdg1rate11")]
        public double? Wdg1rate11 { get; set; }
        [Column("wdg1rate12")]
        public double? Wdg1rate12 { get; set; }
        [Column("wdg1rate2")]
        public double? Wdg1rate2 { get; set; }
        [Column("wdg1rate3")]
        public double? Wdg1rate3 { get; set; }
        [Column("wdg1rate4")]
        public double? Wdg1rate4 { get; set; }
        [Column("wdg1rate5")]
        public double? Wdg1rate5 { get; set; }
        [Column("wdg1rate6")]
        public double? Wdg1rate6 { get; set; }
        [Column("wdg1rate7")]
        public double? Wdg1rate7 { get; set; }
        [Column("wdg1rate8")]
        public double? Wdg1rate8 { get; set; }
        [Column("wdg1rate9")]
        public double? Wdg1rate9 { get; set; }
        [Column("wdg2rate1")]
        public string? Wdg2rate1 { get; set; }
        [Column("wdg2rate10")]
        public string? Wdg2rate10 { get; set; }
        [Column("wdg2rate11")]
        public string? Wdg2rate11 { get; set; }
        [Column("wdg2rate12")]
        public string? Wdg2rate12 { get; set; }
        [Column("wdg2rate2")]
        public string? Wdg2rate2 { get; set; }
        [Column("wdg2rate3")]
        public string? Wdg2rate3 { get; set; }
        [Column("wdg2rate4")]
        public string? Wdg2rate4 { get; set; }
        [Column("wdg2rate5")]
        public string? Wdg2rate5 { get; set; }
        [Column("wdg2rate6")]
        public string? Wdg2rate6 { get; set; }
        [Column("wdg2rate7")]
        public string? Wdg2rate7 { get; set; }
        [Column("wdg2rate8")]
        public string? Wdg2rate8 { get; set; }
        [Column("wdg2rate9")]
        public string? Wdg2rate9 { get; set; }
        [Column("wdg3rate1")]
        public string? Wdg3rate1 { get; set; }
        [Column("wdg3rate10")]
        public string? Wdg3rate10 { get; set; }
        [Column("wdg3rate11")]
        public string? Wdg3rate11 { get; set; }
        [Column("wdg3rate12")]
        public string? Wdg3rate12 { get; set; }
        [Column("wdg3rate2")]
        public string? Wdg3rate2 { get; set; }
        [Column("wdg3rate3")]
        public string? Wdg3rate3 { get; set; }
        [Column("wdg3rate4")]
        public string? Wdg3rate4 { get; set; }
        [Column("wdg3rate5")]
        public string? Wdg3rate5 { get; set; }
        [Column("wdg3rate6")]
        public string? Wdg3rate6 { get; set; }
        [Column("wdg3rate7")]
        public string? Wdg3rate7 { get; set; }
        [Column("wdg3rate8")]
        public string? Wdg3rate8 { get; set; }
        [Column("wdg3rate9")]
        public string? Wdg3rate9 { get; set; }
        [Column("windv1")]
        public double? Windv1 { get; set; }
        [Column("windv2")]
        public double? Windv2 { get; set; }
        [Column("windv3")]
        public string? Windv3 { get; set; }
        [Column("x1_2")]
        public double? X1_2 { get; set; }
        [Column("x2_3")]
        public string? X2_3 { get; set; }
        [Column("x3_1")]
        public string? X3_1 { get; set; }
        [Column("zcod")]
        public string? Zcod { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    [Table("Impcor")]
    public class Impcor
    {
        public Impcor() { }

        public override string ToString() { return this.GetType().Name; }


        [Column("imfact")]
        public double? Imfact { get; set; }
        [Key]
        [Column("itable")]
        public int? Itable { get; set; }
        [Column("refact")]
        public double? Refact { get; set; }
        [Key]
        [Column("tap")]
        public double? Tap { get; set; }
        [Column("CaseNumber")]
        public int CaseNumber { get; set; }

        // Navigation property
        [ForeignKey(nameof(CaseNumber))]
        public virtual CaseInfo CaseNum { get; set; }
    }

    //    [Table("Subterm")]
    //    public class Subterm {
    //        public Subterm() { }

    //        public override string ToString() { return this.GetType().Name; }
    //        [Key]
    //        [Column("eqid")]
    //        public string? Eqid { get; set; }


    //        [Column("ibus")]
    //        public int? Ibus { get; set; }
    //        [Key]
    //        [Column("inode")]
    //        public int? Inode { get; set; }
    //        [Key]
    //        [Column("isub")]
    //        public int? Isub { get; set; }

    //         [Key]
    //        [Column("jbus")]
    //        public string? Jbus { get; set; }

    //        [Column("kbus")]
    //        public string? Kbus { get; set; }
    //        [Key]
    //        [Column("type")]
    //        public string? Type { get; set; }
    //    }


    public static readonly System.Type[] allClasses = new System.Type[]
{
    typeof(Caseid),
    typeof(General),
    typeof(Gauss),
    typeof(Newton),
    typeof(Adjust),
    typeof(Tysl),
    typeof(Rating),
     typeof(Acline),
     typeof(Area),
     typeof(Bus),
     typeof(Facts),
     typeof(Fixshunt),
    //  typeof(Iatransfer),
     typeof(Indmach),
     typeof(Load),
     typeof(Ntermdc),
     typeof(Ntermdcbus),
     typeof(Ntermdcconv),
     typeof(Ntermdclink),
     typeof(Owner),
     typeof(Sub),
     typeof(Subnode),
    //  typeof(Subswd),
     typeof(Swshunt),
     typeof(Sysswd),
     typeof(Twotermdc),
     typeof(Vscdc),
     typeof(Zone),
    //  typeof(Generator),
    //  typeof(Transformer)
    };
}